#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <SOIL.h>
#include "ShaderProgram.h"
#include "Camera.h"
#include "Room.h"
#include "OBJLoader.h"
#include "Model.h"
//#include "SkinnedModel.h"
#include "Mesh.h"
#include "ModelInstance.h"
#include "Environment.h"
#include "Light.h"
#include "Billboard.h"
#include "Texture.h"
#include "ShadowMap.h"
#include "Window.h"
#include "Screen.h"
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
